-- MySQL Script generated by MySQL Workbench
-- Sun Feb 20 22:35:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Crypto
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Crypto` ;

-- -----------------------------------------------------
-- Schema Crypto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Crypto` DEFAULT CHARACTER SET utf8 ;
USE `Crypto` ;

-- -----------------------------------------------------
-- Table `Crypto`.`Currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Crypto`.`Currency` ;

CREATE TABLE IF NOT EXISTS `Crypto`.`Currency` (
  `id` BIGINT(8) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(128) NOT NULL,
  `currencycode` VARCHAR(8) NOT NULL,
  `currencytype` ENUM("fiat", "crypto") NOT NULL DEFAULT 'fiat',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UQ_currencycode` (`currencycode` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crypto`.`CurrencyPair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Crypto`.`CurrencyPair` ;

CREATE TABLE IF NOT EXISTS `Crypto`.`CurrencyPair` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `quotecurrency` BIGINT(8) NOT NULL,
  `basecurrency` BIGINT(8) NOT NULL,
  `description` TEXT(128) NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_currencypair_quotecurrency_idx` (`quotecurrency` ASC) VISIBLE,
  INDEX `FK_currencypair_basecurrency_idx` (`basecurrency` ASC) VISIBLE,
  UNIQUE INDEX `UQ_pair` (`quotecurrency` ASC, `basecurrency` ASC) VISIBLE,
  CONSTRAINT `FK_currencypair_quotecurrency`
    FOREIGN KEY (`quotecurrency`)
    REFERENCES `Crypto`.`Currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_currencypair_basecurrency`
    FOREIGN KEY (`basecurrency`)
    REFERENCES `Crypto`.`Currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crypto`.`QuoteMap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Crypto`.`QuoteMap` ;

CREATE TABLE IF NOT EXISTS `Crypto`.`QuoteMap` (
  `quoteref` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `currencypairid` BIGINT(8) UNSIGNED NOT NULL,
  `datafield` VARCHAR(64) NOT NULL,
  `market` VARCHAR(45) NULL,
  PRIMARY KEY (`quoteref`),
  UNIQUE INDEX `FK_CurrencyPair_idx` (`currencypairid` ASC) VISIBLE,
  UNIQUE INDEX `UQ_pair_field_mkt` (`currencypairid` ASC, `datafield` ASC, `market` ASC) VISIBLE,
  CONSTRAINT `FK_CurrencyPair`
    FOREIGN KEY (`currencypairid`)
    REFERENCES `Crypto`.`CurrencyPair` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Crypto`.`QuoteHistory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Crypto`.`QuoteHistory` ;

CREATE TABLE IF NOT EXISTS `Crypto`.`QuoteHistory` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `timestamp` DATETIME NOT NULL,
  `quote` DECIMAL(25,10) NOT NULL,
  `quoteref` BIGINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_quoteref_idx` (`quoteref` ASC) VISIBLE,
  UNIQUE INDEX `UQ_quote` (`timestamp` ASC, `quoteref` ASC) VISIBLE,
  CONSTRAINT `FK_quoteref`
    FOREIGN KEY (`quoteref`)
    REFERENCES `Crypto`.`QuoteMap` (`quoteref`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
