INSERT INTO Currency (name, currencycode, currencytype) VALUES
("0x","ZRX","crypto"),
("1inch","1INCH","crypto"),
("Aave","AAVE","crypto"),
("Aavegotchi","GHST","crypto"),
("Acala","ACA","crypto"),
("Akash","AKT","crypto"),
("Algorand","ALGO","crypto"),
("Altair","AIR","crypto"),
("Ankr","ANKR","crypto"),
("Aragon","ANT","crypto"),
("Astar","ASTR","crypto"),
("Augur","REP","crypto"),
("Augur v2","REPV2","crypto"),
("Avalanche","AVAX","crypto"),
("Axie Infinity","AXS","crypto"),
("Badger DAO","BADGER","crypto"),
("Balancer","BAL","crypto"),
("Bancor","BNT","crypto"),
("Band Protocol","BAND","crypto"),
("Basic Attention Token","BAT","crypto"),
("Bifrost","BNC","crypto"),
("Bitcoin","BTC","crypto"),
("Bitcoin Cash","BCH","crypto"),
("Bonfida","FIDA","crypto"),
("Cardano","ADA","crypto"),
("Cartesi","CTSI","crypto"),
("Chainlink","LINK","crypto"),
("Chiliz","CHZ","crypto"),
("Compound","COMP","crypto"),
("Cosmos","ATOM","crypto"),
("Covalent","CQT","crypto"),
("Curve","CRV","crypto"),
("Dai*","DAI","crypto"),
("Dash","DASH","crypto"),
("Decentraland","MANA","crypto"),
("Dogecoin","DOGE","crypto"),
("dYdX","DYDX","crypto"),
("Energy Web Token","EWT","crypto"),
("Enjin Coin","ENJ","crypto"),
("Enzyme Finance","MLN","crypto"),
("EOS","EOS","crypto"),
("Ethereum (Ether)","ETH","crypto"),
("Ethereum Classic","ETC","crypto"),
("Filecoin","FIL","crypto"),
("Flow","FLOW","crypto"),
("Gnosis","GNO","crypto"),
("ICON","ICX","crypto"),
("Injective Protocol","INJ","crypto"),
("Karura","KAR","crypto"),
("Kava","KAVA","crypto"),
("Keep Network","KEEP","crypto"),
("KILT","KILT","crypto"),
("Kin","KIN","crypto"),
("Kintsugi","KINT","crypto"),
("Kusama","KSM","crypto"),
("Kyber Network","KNC","crypto"),
("Lisk","LSK","crypto"),
("Litecoin","LTC","crypto"),
("Livepeer","LPT","crypto"),
("Loopring","LRC","crypto"),
("Maker","MKR","crypto"),
("Mango","MNGO","crypto"),
("Mina","MINA","crypto"),
("Mirror Protocol","MIR","crypto"),
("Monero","XMR","crypto"),
("Moonbeam","GLMR","crypto"),
("Moonriver","MOVR","crypto"),
("Nano","NANO","crypto"),
("Ocean","OCEAN","crypto"),
("OmiseGO","OMG","crypto"),
("Orca","ORCA","crypto"),
("Orchid","OXT","crypto"),
("Origin Protocol","OGN","crypto"),
("Oxygen","OXY","crypto"),
("PAX Gold","PAXG","crypto"),
("Perpetual Protocol","PERP","crypto"),
("Phala","PHA","crypto"),
("Polkadot","DOT","crypto"),
("Polygon","MATIC","crypto"),
("Qtum","QTUM","crypto"),
("Rarible","RARI","crypto"),
("Raydium","RAY","crypto"),
("REN Protocol","REN","crypto"),
("Ripple","XRP","crypto"),
("Saber","SBR","crypto"),
("Serum","SRM","crypto"),
("Shiba Inu","SHIB","crypto"),
("Shiden","SDN","crypto"),
("Siacoin","SC","crypto"),
("Solana","SOL","crypto"),
("Star Atlas","ATLAS","crypto"),
("Star Atlas DAO","POLIS","crypto"),
("Stellar Lumens","XLM","crypto"),
("Step Finance","STEP","crypto"),
("Storj","STORJ","crypto"),
("Sushi","SUSHI","crypto"),
("Synthetix","SNX","crypto"),
("tBTC","TBTC","crypto"),
("Terra","LUNA","crypto"),
("TerraUSD","UST","crypto"),
("Tether*","USDT","crypto"),
("Tezos","XTZ","crypto"),
("The Graph","GRT","crypto"),
("The Sandbox","SAND","crypto"),
("Tron","TRX","crypto"),
("Uniswap","UNI","crypto"),
("USD Coin*","USDC","crypto"),
("WAVES","WAVES","crypto"),
("Wrapped Bitcoin","WBTC","crypto"),
("Yearn Finance","YFI","crypto"),
("Zcash","ZEC","crypto");