INSERT INTO Currency (name, currencycode, currencytype) VALUES
("Australian dollar","AUD","fiat"),
("Bulgarian lev","BGN","fiat"),
("Brazilian real","BRL","fiat"),
("Canadian dollar","CAD","fiat"),
("Swiss franc","CHF","fiat"),
("Chinese yuan","CNY","fiat"),
("Cypriot pound","CYP","fiat"),
("Czech krona","CZK","fiat"),
("Danish krona","DKK","fiat"),
("Estonian kroon","EEK","fiat"),
("British pound","GBP","fiat"),
("Hong Kong dollar","HKD","fiat"),
("Croatian kuna","HRK","fiat"),
("Hungarian florint","HUF","fiat"),
("Indonesian rupiah","IDR","fiat"),
("Israeli shekel","ILS","fiat"),
("Indian rupee","INR","fiat"),
("Icelandic krona","ISK","fiat"),
("Japanese yen","JPY","fiat"),
("Korean won","KRW","fiat"),
("Lithuanian litas","LTL","fiat"),
("Latvian lats","LVL","fiat"),
("Maltese lira","MTL","fiat"),
("Mexican peso","MXN","fiat"),
("Malaysian ringit","MYR","fiat"),
("Norwegian krona","NOK","fiat"),
("New Zealand dollar","NZD","fiat"),
("Philippine peso","PHP","fiat"),
("Polish zloty","PLN","fiat"),
("Romanian leu","ROL","fiat"),
("Romanian leu","RON","fiat"),
("Russian ruble","RUB","fiat"),
("Swedish krona","SEK","fiat"),
("Singapore dollar","SGD","fiat"),
("Slovenian tolar","SIT","fiat"),
("Slovak koruna","SKK","fiat"),
("Thai baht","THB","fiat"),
("Turkish lira","TRL","fiat"),
("Turkish lira","TRY","fiat"),
("US dollar","USD","fiat"),
("South African rand","ZAR","fiat");