use Crypto;
select min(id), max(id) from CryptoCurrencyPair;


INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Bitcoin', 'BTC', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Ethereum', 'ETH', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Cardano', 'ADA', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Tether USD', 'USDT', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Ripple', 'XRP', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Dogecoin', 'DOGE', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('USD Coin', 'USDC', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Polkadot', 'DOT', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Solana', 'SOL', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Uniswap', 'UNI', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Bitcoin Cash', 'BCH', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Litecoin', 'LTC', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Chainlink', 'LINK', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Wrapped Bitcoin', 'WBTC', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Polygon', 'MATIC', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Lumen', 'XLM', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Ethereum Classic', 'ETC', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Filecoin', 'FIL', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('TRON', 'TRX', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Dai', 'DAI', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Monero', 'XMR', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Aave', 'AAVE', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('EOS', 'EOS', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Axie Infinity Shards', 'AXS', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('The Graph', 'GRT', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Cosmos', 'ATOM', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Tezos', 'XTZ', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('MakerDAO', 'MKR', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Algorand', 'ALGO', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Waves', 'WAVES', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Dash', 'DASH', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Kusama', 'KSM', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Compound', 'COMP', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Chiliz', 'CHZ', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Zcash', 'ZEC', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Decentra land', 'MANA', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Enjin', 'ENJ', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Sushi', 'SUSHI', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Synthetix', 'SNX', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Yearn Finance', 'YFI', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Flow', 'FLOW', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Basic Attention Token', 'BAT', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Qtum', 'QTUM', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Siacoin', 'SC', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Bancor', 'BNT', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Perpetual Protocol', 'PERP', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('0x', 'ZRX', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('ICON', 'ICX', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Curve DAO Token', 'CRV', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('OMG Network', 'OMG', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Nano', 'NANO', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Ankr', 'ANKR', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Loopring', 'LRC', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Kava', 'KAVA', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Sand', 'SAND', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Mina', 'MINA', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Ren', 'REN', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('1inch', '1INCH', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Lisk', 'LSK', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('OCEAN Token', 'OCEAN', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Gnosis', 'GNO', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Storj', 'STORJ', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('LivePeer', 'LPT', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Injective Protocol', 'INJ', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Origin Protocol', 'OGN', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Kyber Network', 'KNC', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('PAX Gold', 'PAXG', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Serum', 'SRM', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Energy Web Token', 'EWT', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Band Protocol', 'BAND', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Augur', 'REP', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Augur v2', 'REPV2', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Cartesi', 'CTSI', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Mirror Protocol', 'MIR', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Orchid', 'OXT', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Keep Network', 'KEEP', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Enzyme Finance', 'MLN', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Badger DAO', 'BADGER', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Aragon', 'ANT', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Balancer', 'BAL', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Rarible', 'RARI', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Aavegotchi', 'GHST', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Covalent', 'CQT', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Karura', 'KAR', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('tBTC', 'TBTC', 'USD');
INSERT INTO CryptoCurrencyPair(name, quotecurrency, basecurrency) VALUES ('Ethereum 2.0', 'ETH2', 'USD');
